# Generated by Django 3.2.1 on 2021-10-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='order',
        ),
    ]
